services:
  - type: web
    name: monthly-spend-pwa
    runtime: docker
    plan: free
    region: singapore
    branch: orion/main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: APP_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_DRIVE_RECEIPT_FOLDER_ID
        sync: false
      - key: GOOGLE_DRIVE_FOOD_FOLDER_ID
        value: 1YqbaLKhPhz8TMNh1vL4FLiDGvYaMapM8
      - key: GOOGLE_DRIVE_SPEND_FOLDER_ID
        value: 10svWmFf_0kEZDn8TIHxnYyZ7VLAoS2m0
      - key: SPREADSHEET_ID
        value: 1TpB2iMLGiJzzz2trmitq2hGZLDOQ120gndDJuDqLBJk
      - key: SHEET_NAME
        value: "Monthy Spend "
      - key: APP_CORS_ALLOWED_ORIGINS
        value: "https://localhost"
